version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: DocNearMe-postgres
    restart: always
    environment:
      - POSTGRES_DB=DocNearMe
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    networks:
      - jenkins_network
    volumes:
      - db_data:/var/lib/postgresql/data  # Keep this volume for the DocNearMe database

  sonar-postgres:
    image: postgres:latest
    container_name: DocNearMe-sonar-postgres
    restart: always
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    ports:
      - "5433:5433"
    networks:
      - jenkins_network

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: DocNearMe-jenkins
    privileged: true
    user: root
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Keep this bind mount for Docker socket
    networks:
      - jenkins_network

  sonarqube:
    image: sonarqube:latest
    container_name: DocNearMe-sonarqube
    restart: always
    depends_on:
      - sonar-postgres
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonar-postgres:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    ports:
      - "9000:9000"
    networks:
      - jenkins_network

networks:
  jenkins_network:

volumes:
  db_data:  # Keep this volume for the DocNearMe database